SLIDE_PATH: '/project/hnguyen2/hqvo3/Datasets/digital_pathology/public/CAMELYON16/images/project/hnguyen2/hqvo3/Datasets/digital_pathology/public/CAMELYON16/images' #replace you path 
JSON_PATH: '/project/hnguyen2/mvu9/camelyon16/json_files_v2' # replace your path 
# JSON_PATH: '/project/hnguyen2/mvu9/camelyon16/json_files' # replace your path 
SPIXEL_PATH: '/project/hnguyen2/mvu9/camelyon16/spixel_paths'
PATCH_PATH: '/project/hnguyen2/mvu9/camelyon16/patch_paths'
FEATURES_H5_PATH: '/project/hnguyen2/mvu9/camelyon16/features_h5_files' 
CHECKPOINT_PATH: '/project/hnguyen2/mvu9/camelyon16/checkpoints'
IMPORTANT_SCORES_PATH: '/project/hnguyen2/mvu9/camelyon16/important_scores_path'
IMPORTANT_SCORES_PATH2: '/project/hnguyen2/mvu9/camelyon16/important_scores_path2' 
PLOT_PATH: '/project/hnguyen2/mvu9/camelyon16/plotting'
FEATURE_MEAN_STD_PATH: '/project/hnguyen2/mvu9/camelyon16/feature_mean_std_path/mean_std.h5'
ANNOTATION_PATH: '/project/hnguyen2/hqvo3/Datasets/digital_pathology/public/CAMELYON16/annotations'
LABEL_PATH: '/project/hnguyen2/hqvo3/Datasets/digital_pathology/public/CAMELYON16/evaluation/reference.csv'
SPLIT_PATH: '/project/hnguyen2/mvu9/camelyon16/camelyon_csv_splits/splits_3.csv'
batch_size: 256
patch_size: 224 
feature_extraction_model: 'vit_base_patch16_224'
SANITY_CHECK_PATH: '/project/hnguyen2/mvu9/camelyon16/sanity_check'  
GROUND_TRUTH_CORR_PATH: '/project/hnguyen2/mvu9/camelyon16/ground_truth_corr'   
GROUND_TRUTH_PATH: '/project/hnguyen2/mvu9/camelyon16/ground_truth_mask' 
SCORE_FOLDER: '/project/hnguyen2/mvu9/camelyon16/attribution_scores'
PLOT_PATH_DRYRUN: '/project/hnguyen2/mvu9/camelyon16/plotting_dryrun'
SCORE_FOLDER_DRYRUN: '/project/hnguyen2/mvu9/camelyon16/attribution_scores_dryrun'   