SLIDE_PATH: '/mnt/dataset1/ngoc/camelyon16/images' #replace you path 
JSON_PATH: '/mnt/dataset1/ngoc/camelyon16/json_files' # replace your path 
SPIXEL_PATH: '/mnt/dataset1/ngoc/camelyon16/spixel_paths'
PATCH_PATH: '/mnt/dataset1/ngoc/camelyon16/patch_paths'
FEATURES_H5_PATH: '/mnt/dataset1/ngoc/camelyon16/features_5h_files' 
scoring_function: get_scoring_do_nothing 
pruning_function: get_pruning_do_nothing
batch_size: 256
patch_size: 224 
feature_extraction_model: 'vit_base_patch16_224' 