SLIDE_PATH: '/Users/mfv-computer-0261/Desktop/tmp/images'
JSON_PATH: '/Users/mfv-computer-0261/Desktop/tmp/json_files_v2' # replace your path 
SPIXEL_PATH: '/Users/mfv-computer-0261/Desktop/tmp/spixel_paths'
PATCH_PATH: '/Users/mfv-computer-0261/Desktop/tmp/patch_paths'
FEATURES_H5_PATH: '/Users/mfv-computer-0261/Desktop/tmp/features_h5_files' 
CHECKPOINT_PATH: '/Users/mfv-computer-0261/Desktop/tmp/checkpoints'
IMPORTANT_SCORES_PATH: '/Users/mfv-computer-0261/Desktop/tmp/important_scores_path'
IMPORTANT_SCORES_PATH2: '/Users/mfv-computer-0261/Desktop/tmp/important_scores_path2' 
PLOT_PATH: '/Users/mfv-computer-0261/Desktop/tmp/plotting'
FEATURE_MEAN_STD_PATH: '/Users/mfv-computer-0261/Desktop/tmp/mean_std.h5'
ANNOTATION_PATH: '/Users/mfv-computer-0261/Desktop/tmp/annotations'
LABEL_PATH: '/Users/mfv-computer-0261/Desktop/tmp/reference.csv'
SPLIT_PATH: '/Users/mfv-computer-0261/Desktop/tmp/splits_3.csv'
batch_size: 256
patch_size: 224 
feature_extraction_model: 'vit_base_patch16_224'
SANITY_CHECK_PATH: '/Users/mfv-computer-0261/Desktop/tmp/sanity_check'  
# GROUND_TRUTH_CORR_PATH: '/project/hnguyen2/mvu9/camelyon16/ground_truth_corr'   
# GROUND_TRUTH_PATH: '/project/hnguyen2/mvu9/camelyon16/ground_truth_mask' 
# SCORE_FOLDER: '/project/hnguyen2/mvu9/camelyon16/attribution_scores'
PLOT_PATH_DRYRUN: '/Users/mfv-computer-0261/Desktop/tmp/plotting_dryrun'
SCORE_FOLDER_DRYRUN: '/Users/mfv-computer-0261/Desktop/tmp/attribution_scores_dryrun'  
MEMMAP_PATH:  '/Users/mfv-computer-0261/Desktop/tmp/memmap'
SCORE_FOLDER: '/Users/mfv-computer-0261/Desktop/tmp/attribution_scores_ver2' 
GROUND_TRUTH_CORR_PATH: '/Users/mfv-computer-0261/Desktop/tmp/ground_truth_corr_ver2'    
GROUND_TRUTH_PATH: '/Users/mfv-computer-0261/Desktop/tmp/ground_truth_mask_ver2' 
PRED_PATH: '/project/hnguyen2/mvu9/camelyon16/pred_on_testset.csv' 